plugin_sets:
  bipedal:
    # GaitGeneratorPlugin
    bipedal_gait_generator: none
    
    # StateGeneratorPlugin    
    direct_goal_state_generator: none
    polygonal_state_generator_high:
      import: polygonal_state_generator
      params:
        reachability_polygons: &reachability_polygons
          base_polygon: &base_polygon
            - x: [ 0.00, -0.05, -0.20, -0.17, -0.13,  0.13,  0.20,  0.38,  0.20]
              y: [-0.02, -0.02,  0.00,  0.10,  0.15,  0.15,  0.10,  0.00, -0.02]
              yaw: [-0.30, 0.40]

          feet:
            - <<: *base_polygon
              idx: 0 # left

            - <<: *base_polygon
              idx: 1 # right
              mirror_y: True
              mirror_yaw: True

    # ReachabilityPlugins
    state_3d_reachability:
      params:
        max_foothold_roll: 0.25
        max_foothold_pitch: 0.25
    polygonal_reachability:
      params:
        reachability_polygons: *reachability_polygons
    support_polygon_check:
      params:
        support_polygons:
          base_support_polygon: &base_support_polygon
            - x: [-0.09, -0.07, -0.02,  0.02,  0.07,  0.09]
              y: [-0.07,  0.0,   0.05,  0.05,  0.0,  -0.07]

          feet:
            - <<: *base_support_polygon
              idx: 0 # left

            - <<: *base_support_polygon
              idx: 1 # right
              mirror_y: True
              mirror_yaw: True

    # StepCostEstimatorPlugins
    const_step_cost_estimator:
      params:
        step_cost: &step_cost 0.1
    euclidean_step_cost_estimator: none
    #ground_contact_step_cost_estimator: none

    # HeuristicPlugins
    euclidean_heuristic: none
    step_cost_heuristic:
      params:
        step_cost: *step_cost
        diff_angle_cost: 0.05
        max_step_dist_x: 0.38
        max_step_dist_y: 0.15

    # PostProcessPlugins
    #ground_contact_post_process:
    #  params:
    #    min_sampling_steps_x: 6
    #    min_sampling_steps_y: 4
    #    max_sampling_steps_x: 16
    #    max_sampling_steps_y: 12
    #    max_intrusion_z: 0.03
    #    max_ground_clearance: 0.02
    #    minimal_support: 0.9
    step_dynamics_post_process:
      params:
        sway_duration: 0.10
        step_duration: 2.00
        swing_height:  0.10

    # WorldModelPlugins
    1_upper_body_grid_map_model:
      import: upper_body_grid_map_model
      params:
        collision_check_flag: 2 # Upper Body
        topic: /body_level_grid_map
    2_foot_grid_map_model:
      import: foot_grid_map_model
      params:
        collision_check_flag: 1 # Foot
        topic: /ground_level_grid_map

    # TerrainModelPlugins
    terrain_model:
      import: basic_terrain_model

  vis:
    step_plan_request_vis: none
    step_plan_vis: none
    step_plan_path_vis: none
    upper_body_vis: none
    ground_contact_estimation_vis: none
    planning_feedback_vis: none
    nav_goal_marker_vis:
      params:
        step_controller_topic: /l3/execute_step_plan
