#!/usr/bin/env python

import sys

pkg = 'l3_footstep_planning_widgets'
widget = 'parameter_editor_rqt_widget'

from rqt_gui.main import Main

main = Main()
sys.exit(main.main(sys.argv, standalone=pkg+'.'+widget))
